// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package dbcontext

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteCompany(ctx context.Context, id pgtype.UUID) error
	GetCompany(ctx context.Context, id pgtype.UUID) (Company, error)
	NewCompany(ctx context.Context, arg NewCompanyParams) (pgtype.UUID, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) error
}

var _ Querier = (*Queries)(nil)
